# Generated by Django 4.2.7 on 2025-08-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('course', models.CharField(choices=[('appetizer', '🥗 Przystawka'), ('soup', '🍲 Zupa'), ('main', '🍖 Danie główne'), ('dessert', '🍰 Deser'), ('drink', '🥤 Napój')], max_length=20, verbose_name='Kategoria')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cena')),
                ('allergens', models.CharField(blank=True, max_length=200, verbose_name='Alergeny')),
                ('vegetarian', models.BooleanField(default=False, verbose_name='Wegetariańskie')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Pozycja Menu',
                'verbose_name_plural': 'Pozycje Menu',
                'ordering': ['course', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('start_time', models.TimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Czas zakończenia')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Miejsce')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Numer stołu')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nazwa stołu')),
                ('capacity', models.IntegerField(default=8, verbose_name='Miejsca')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('map_x', models.FloatField(default=300, help_text='Współrzędna X na mapie (0-900)', verbose_name='Pozycja X')),
                ('map_y', models.FloatField(default=300, help_text='Współrzędna Y na mapie (0-600)', verbose_name='Pozycja Y')),
                ('map_width', models.FloatField(default=85, help_text='Szerokość stołu na mapie', verbose_name='Szerokość')),
                ('map_height', models.FloatField(default=85, help_text='Wysokość stołu na mapie', verbose_name='Wysokość')),
                ('shape', models.CharField(choices=[('circular', 'Okrągły'), ('rectangular', 'Prostokątny'), ('square', 'Kwadratowy')], default='circular', max_length=20, verbose_name='Kształt stołu')),
                ('color', models.CharField(default='#d4c4a8', help_text='Kolor w formacie hex np. #d4c4a8', max_length=7, verbose_name='Kolor')),
                ('border_color', models.CharField(default='#b8a082', help_text='Kolor obramowania hex', max_length=7, verbose_name='Kolor obramowania')),
            ],
            options={
                'verbose_name': 'Stół',
                'verbose_name_plural': 'Stoły',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100, verbose_name='Imię Panny Młodej')),
                ('groom_name', models.CharField(max_length=100, verbose_name='Imię Pana Młodego')),
                ('wedding_date', models.DateField(verbose_name='Data Ślubu')),
                ('venue_name', models.CharField(max_length=200, verbose_name='Miejsce Wesela')),
                ('welcome_message', models.TextField(verbose_name='Wiadomość Powitalna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Informacje o Weselu',
                'verbose_name_plural': 'Informacje o Weselu',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Zdjęcie')),
                ('category', models.CharField(choices=[('ceremony', '💒 Ceremonia'), ('reception', '🎉 Przyjęcie'), ('party', '💃 Zabawa'), ('preparations', '👗 Przygotowania'), ('family', '👨\u200d👩\u200d👧\u200d👦 Rodzina'), ('friends', '👥 Przyjaciele'), ('other', '📷 Inne')], default='other', max_length=20, verbose_name='Kategoria')),
                ('uploader_name', models.CharField(blank=True, help_text='Dla gości bez konta', max_length=100, verbose_name='Imię przesyłającego')),
                ('approved', models.BooleanField(default=False, verbose_name='Zatwierdzone')),
                ('featured', models.BooleanField(default=False, verbose_name='Wyróżnione')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_photos', to=settings.AUTH_USER_MODEL, verbose_name='Przesłane przez')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Numer telefonu')),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name='Numer stołu')),
                ('guest_type', models.CharField(blank=True, max_length=50, verbose_name='Typ gościa')),
                ('dietary_requirements', models.TextField(blank=True, verbose_name='Wymagania dietetyczne')),
                ('plus_one', models.BooleanField(default=False, verbose_name='Osoba towarzysząca')),
                ('confirmed', models.BooleanField(default=True, verbose_name='Potwierdzony')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gość',
                'verbose_name_plural': 'Goście',
            },
        ),
    ]
