# Generated by Django 4.2.7 on 2025-08-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Typ gościa'),
        ),
    ]
