# Generated by Django 4.2.7 on 2025-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='chair_position',
            field=models.IntegerField(blank=True, help_text='Pozycja krzesła przy stole (1-N)', null=True, verbose_name='Pozycja krzesła'),
        ),
    ]
