# Generated by Django 4.2.7 on 2025-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_guest_guest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='border_color',
            field=models.CharField(default='#b8a082', help_text='Kolor obramowania hex', max_length=7, verbose_name='Kolor obramowania'),
        ),
        migrations.AddField(
            model_name='table',
            name='color',
            field=models.CharField(default='#d4c4a8', help_text='Kolor w formacie hex np. #d4c4a8', max_length=7, verbose_name='Kolor'),
        ),
        migrations.AddField(
            model_name='table',
            name='map_height',
            field=models.FloatField(default=85, help_text='Wysokość stołu na mapie', verbose_name='Wysokość'),
        ),
        migrations.AddField(
            model_name='table',
            name='map_width',
            field=models.FloatField(default=85, help_text='Szerokość stołu na mapie', verbose_name='Szerokość'),
        ),
        migrations.AddField(
            model_name='table',
            name='map_x',
            field=models.FloatField(default=300, help_text='Współrzędna X na mapie (0-900)', verbose_name='Pozycja X'),
        ),
        migrations.AddField(
            model_name='table',
            name='map_y',
            field=models.FloatField(default=300, help_text='Współrzędna Y na mapie (0-600)', verbose_name='Pozycja Y'),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('circular', 'Okrągły'), ('rectangular', 'Prostokątny'), ('square', 'Kwadratowy')], default='circular', max_length=20, verbose_name='Kształt stołu'),
        ),
    ]
