# Generated by Django 4.2.7 on 2025-08-28 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wedding', '0003_table_border_color_table_color_table_map_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploader_name',
            field=models.CharField(blank=True, help_text='Dla gości bez konta', max_length=100, verbose_name='Imię przesyłającego'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Przesłane przez'),
        ),
    ]
